services:

  ghost:
    # image: ghost-s3:latest
    image: beevk/ghost-s3:latest
    restart: always
    ports:
      - 2368:2368
    environment:
      # # see https://ghost.org/docs/config/#configuration-options
      # database__client: mysql
      # database__connection__host: db
      # database__connection__user: user1
      # database__connection__password: secretPassword
      # database__connection__database: ghost

      url: http://localhost:2368 # Change this

      NODE_ENV: development # default: production

      storage__active: s3
      storage__s3__accessKeyId: ${S3_ACCESS_KEY_ID} # Change this
      storage__s3__secretAccessKey: ${S3_SECRET_ACCESS_KEY} # Change this
      storage__s3__region: ${S3_REGION} # Change this
      storage__s3__bucket: ${S3_BUCKET} # Change this
      storage__s3__assetHost: ${S3_ASSET_HOST} # Change this
      storage__s3__pathPrefix: ${S3_PATH_PREFIX} # Optional, Set this if you want all images to be stored in a subfolder
      storage__s3__forcePathStyle: true
      storage__s3__acl: private
    volumes:
      - ghost:/var/lib/ghost/content

volumes:
  ghost:
